export const EXAMPLE = 'EXAMPLE';



//cart 页面所需常量

export const INITCART = 'INITCART';
export const CHANGENUM = 'CHANGENUM';
export const CARTDELETE = 'CARTDELETE';

//order generate 页面

export const INITORDERGENERATE = 'INITORDERGENERATE';
export const INITADDRESS = 'INITADDRESS';
export const SETDEFAULTADDRESS = 'SETDEFAULTADDRESS';
export const SETISREGISTER = 'SETISREGISTER';
export const SETREMARK = 'SETREMARK';

//地址相關
export const ADDNEWADDRESS = 'ADDNEWADDRESS';
export const DELETEADDRESS = 'DELETEADDRESS';
export const UPDATEADDRESS = 'UPDATEADDRESS';
export const EDITADDRESS = 'EDITADDRESS';
export const SHOWADDADDRESS = 'SHOWADDADDRESS';
export const CLOSEADDADDRESS = 'CLOSEADDADDRESS';




// product detail 頁面


export const ADD_TO_SHOPING_CAR_SUCCESS = 'ADD_TO_SHOPING_CART_SUCCESS';
export const ADD_TO_SHOPING_CAR_FAILED = 'ADD_TO_SHOPING_CART_FAILED';
export const CHANGE_GOODS_MODEL = 'CHANGE_GOODS_MODEL';
export const CLICK_MODEL_BUTTON = 'CLICK_MODEL_BUTTON';
export const GET_GOODS_DATA_SUCCESS = 'GET_GOODS_DATA_SUCCESS';
export const GET_GOODS_DATA_FAILED = 'GET_GOODS_DATA_FAILED';
export const ADD_SELECTED_MODEL = 'ADD_SELECTED_MODEL'
export const INITIAL_MODEL = 'INITIAL_MODEL';
export const DELETE_SELECTED_MODEL = 'DELETE_SELECTED_MODEL';
export const HANDLE_BUY_NUM = 'HANDLE_BUY_NUM';


//searchResult 


export const GET_SEARCH_RESULT_SUCCESS = 'GET_SEARCH_RESULT_SUCCESS';
export const GET_SEARCH_RESULT_FAILED = 'GET_SEARCH_RESULT_FAILED';


//search 

export const SEARCH_BY_TEXT_SUCCESS = 'SEARCH_BY_TEXT_SUCCESS';

export const SEARCH_BY_TEXT_FAILED = "SEARCH_BY_TEXT_FAILED";

export const SELECT_SEARCH_KEY = "SELECT_SEARCH_KEY";

export const CANCEL_SEARCH_KEY = "CANCEL_SEARCH_KEY";


export const CHANGE_SELECT_KEY = "CHANGE_SELECT_KEY";


export const GET_PRODUCTSCLASS_SUCCESS = "GET_PRODECTSCLASS_SUCCESS";

export const GET_PRODUCTSCLASS_FAILED = "GET_PRODECTSCLASS_FAILED";

export const GET_ALL_BRANDS_SUCCESS = "GET_ALL_BRANDS_SUCCESS";

export const GET_ALL_BRANDS_FAILED = "GET_ALL_BRANDS_FAILED";

export const GET_CATEGORY_BY_USER = "GET_CATEGORY_BY_USER";

export const GET_BRANDS_BY_USER = "GET_BRANDS_BY_USER";

export const GET_TEXT_BY_USER = "GET_TEXT_BY_USER";
export const CHANGE_SELECT_KEY = "CHANGE_SELECT_KEY";
export const CHANGE_SELECT_KEY = "CHANGE_SELECT_KEY";

// index 页面所需常量

export const LAYOUTBRAND = 'LAYOUTBRAND';
export const GETHOTPRODUCT = 'GETHOTPRODUCT';
export const PROMPTIONLIST = 'PROMPTIONLIST';