export const EXAMPLE = 'EXAMPLE';

//cart 页面所需常量
export const INITCART = 'INITCART';
export const CHANGENUM = 'CHANGENUM';
export const CARTDELETE = 'CARTDELETE';


// product detail 頁面

export const ADD_TO_SHOPING_CAR_SUCCESS = 'ADD_TO_SHOPING_CART_SUCCESS';
export const ADD_TO_SHOPING_CAR_FAILED = 'ADD_TO_SHOPING_CART_FAILED';
export  const CHANGE_GOODS_MODEL = 'CHANGE_GOODS_MODEL';
export const CLICK_MODEL_BUTTON = 'CLICK_MODEL_BUTTON';
export const GET_GOODS_DATA_SUCCESS = 'GET_GOODS_DATA_SUCCESS';
export const GET_GOODS_DATA_FAILED ='GET_GOODS_DATA_FAILED';
export const ADD_SELECTED_MODEL ='ADD_SELECTED_MODEL'
export const INITIAL_MODEL = 'INITIAL_MODEL';
export const DELETE_SELECTED_MODEL = 'DELETE_SELECTED_MODEL';
export const HANDLE_BUY_NUM = 'HANDLE_BUY_NUM';

